/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentDataCard: typeof import('./components/eventlog/AgentDataCard.vue')['default']
    AgentRegistrationCard: typeof import('./components/eventlog/AgentRegistrationCard.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AwarenessMapCanvas: typeof import('./components/AwarenessMapCanvas.vue')['default']
    BufferInformationCard: typeof import('./components/eventlog/BufferInformationCard.vue')['default']
    CommandAssignedCard: typeof import('./components/eventlog/CommandAssignedCard.vue')['default']
    CommandClearedCard: typeof import('./components/eventlog/CommandClearedCard.vue')['default']
    CommandDispatchedCard: typeof import('./components/eventlog/CommandDispatchedCard.vue')['default']
    CommandGeneratedCard: typeof import('./components/eventlog/CommandGeneratedCard.vue')['default']
    DriveControlErrorCard: typeof import('./components/eventlog/DriveControlErrorCard.vue')['default']
    ErrorDetail: typeof import('./components/eventlog/ErrorDetail.vue')['default']
    EventCard: typeof import('./components/eventlog/EventCard.vue')['default']
    Go2RtcWebRtc: typeof import('./components/Go2RtcWebRtc.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InteractiveMapCanvas: typeof import('./components/InteractiveMapCanvas.vue')['default']
    ManagerStateWidget: typeof import('./components/ManagerStateWidget.vue')['default']
    MapControlErrorCard: typeof import('./components/eventlog/MapControlErrorCard.vue')['default']
    MapUpdatedCard: typeof import('./components/eventlog/MapUpdatedCard.vue')['default']
    PositionChip: typeof import('./components/PositionChip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignalRTest: typeof import('./components/SignalRTest.vue')['default']
    TimestampChip: typeof import('./components/TimestampChip.vue')['default']
    UsbStartedCard: typeof import('./components/eventlog/UsbStartedCard.vue')['default']
    WaypointTable: typeof import('./components/eventlog/WaypointTable.vue')['default']
    WorkerStateWidget: typeof import('./components/WorkerStateWidget.vue')['default']
  }
}
