/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/awarenessmap': RouteRecordInfo<'/awarenessmap', '/awarenessmap', Record<never, never>, Record<never, never>>,
    '/chat-app': RouteRecordInfo<'/chat-app', '/chat-app', Record<never, never>, Record<never, never>>,
    '/command-center': RouteRecordInfo<'/command-center', '/command-center', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/drive-control': RouteRecordInfo<'/drive-control', '/drive-control', Record<never, never>, Record<never, never>>,
    '/event-log': RouteRecordInfo<'/event-log', '/event-log', Record<never, never>, Record<never, never>>,
    '/fleet-management': RouteRecordInfo<'/fleet-management', '/fleet-management', Record<never, never>, Record<never, never>>,
    '/leadvehicle-detail': RouteRecordInfo<'/leadvehicle-detail', '/leadvehicle-detail', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/setup': RouteRecordInfo<'/setup', '/setup', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/awarenessmap.vue': {
      routes: '/awarenessmap'
      views: never
    }
    'src/pages/chat-app.vue': {
      routes: '/chat-app'
      views: never
    }
    'src/pages/command-center.vue': {
      routes: '/command-center'
      views: never
    }
    'src/pages/dashboard.vue': {
      routes: '/dashboard'
      views: never
    }
    'src/pages/drive-control.vue': {
      routes: '/drive-control'
      views: never
    }
    'src/pages/event-log.vue': {
      routes: '/event-log'
      views: never
    }
    'src/pages/fleet-management.vue': {
      routes: '/fleet-management'
      views: never
    }
    'src/pages/leadvehicle-detail.vue': {
      routes: '/leadvehicle-detail'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/setup.vue': {
      routes: '/setup'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
